apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-tls
  namespace: default             ## MUST match the Ingress ns 
data:
  tls.crt: base64 encoded cert   ## not path but the actual file content 
  tls.key: base64 encoded key   ## not path but the actual file content 
type: kubernetes.io/tls